// Emits TypeScript ABI-only modules from the Hardhat artifacts, so consumers get
// `as const` typing (wagmi/viem infer argument and return types from it) without
// bundling contract bytecode. Run automatically by `pnpm compile`.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

/** [contract name, source path under contracts/]. */
const contracts = [
  ['Coin', 'Coin.sol'],
  ['CoinFactory', 'CoinFactory.sol'],
  ['CoinCreator', 'CoinCreator.sol'],
  ['FeeEscrow', 'FeeEscrow.sol'],
  ['HolderRewards', 'HolderRewards.sol'],
  ['OutbidMarket', 'OutbidMarket.sol'],
  ['Treasury', 'Treasury.sol'],
  ['PonsBuybackVenue', 'PonsBuybackVenue.sol'],
  ['RevenueRouter', 'RevenueRouter.sol'],
  ['OutbidBuyback', 'OutbidBuyback.sol'],
  ['CoinListingManager', 'CoinListingManager.sol'],
  ['LiquidityManager', 'LiquidityManager.sol'],
  ['WETH9', 'WETH9.sol'],
  ['UniswapV3Factory', 'uniswap-v3/core/UniswapV3Factory.sol'],
  ['UniswapV3Pool', 'uniswap-v3/core/UniswapV3Pool.sol'],
  ['SwapRouter', 'uniswap-v3/periphery/SwapRouter.sol'],
  ['QuoterV2', 'uniswap-v3/periphery/lens/QuoterV2.sol'],
  ['SwapExecutor', 'SwapExecutor.sol'],
  ['UniversalRouterAdapter', 'UniversalRouterAdapter.sol'],
  ['ProtocolRegistry', 'ProtocolRegistry.sol'],
];

mkdirSync(join(packageRoot, 'abi'), { recursive: true });

const index = [];
for (const [name, source] of contracts) {
  const artifactPath = join(packageRoot, 'artifacts/contracts', source, `${name}.json`);
  const { abi } = JSON.parse(readFileSync(artifactPath, 'utf8'));
  const constName = name.charAt(0).toLowerCase() + name.slice(1) + 'Abi';
  const file = join(packageRoot, 'abi', `${name}.ts`);
  writeFileSync(
    file,
    `// Generated by scripts/generate-abi.mjs from artifacts/contracts/${source}. Do not edit.\n` +
      `export const ${constName} = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
  index.push(`export { ${constName} } from './${name}';`);
  console.log(`abi/${name}.ts`);
}
writeFileSync(join(packageRoot, 'abi', 'index.ts'), index.join('\n') + '\n');
