// Generated by scripts/generate-abi.mjs from artifacts/contracts/CoinFactory.sol. Do not edit.
export const coinFactoryAbi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "listingManager_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "feeEscrow_",
        "type": "address"
      },
      {
        "internalType": "contract CoinCreator",
        "name": "coinCreator_",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "rewardsImplementation_",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "FailedDeployment",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "balance",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "needed",
        "type": "uint256"
      }
    ],
    "name": "InsufficientBalance",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "owner",
        "type": "address"
      }
    ],
    "name": "OwnableInvalidOwner",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "OwnableUnauthorizedAccount",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "SafeERC20FailedOperation",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "string",
        "name": "nickname",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "profilePicture",
        "type": "string"
      }
    ],
    "name": "AccountInfoUpdated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint16",
        "name": "feeBps",
        "type": "uint16"
      },
      {
        "indexed": false,
        "internalType": "uint16",
        "name": "protocolShareBps",
        "type": "uint16"
      },
      {
        "indexed": false,
        "internalType": "uint16",
        "name": "maxCreatorTaxBps",
        "type": "uint16"
      },
      {
        "indexed": false,
        "internalType": "uint16",
        "name": "snipeTaxStartBps",
        "type": "uint16"
      },
      {
        "indexed": false,
        "internalType": "uint32",
        "name": "snipeTaxSeconds",
        "type": "uint32"
      }
    ],
    "name": "FeeTermsSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "launchFee",
        "type": "uint256"
      }
    ],
    "name": "LaunchFeeSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "creator",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "memecoin",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "quoteAsset",
        "type": "address"
      }
    ],
    "name": "MemeCoinDeployed",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "previousOwner",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "OwnershipTransferred",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint16",
        "name": "virtualQuoteBps",
        "type": "uint16"
      },
      {
        "indexed": false,
        "internalType": "uint128",
        "name": "virtualTokenReserve",
        "type": "uint128"
      },
      {
        "indexed": false,
        "internalType": "uint128",
        "name": "maxSupply",
        "type": "uint128"
      }
    ],
    "name": "ParametersSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint96",
        "name": "cap",
        "type": "uint96"
      },
      {
        "indexed": false,
        "internalType": "uint8",
        "name": "decimals",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "enabled",
        "type": "bool"
      }
    ],
    "name": "QuoteAssetSet",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "memecoin",
        "type": "address"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "distributor",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint16",
        "name": "rewardFeeBps",
        "type": "uint16"
      },
      {
        "indexed": false,
        "internalType": "bool",
        "name": "shareFeesWithHolders",
        "type": "bool"
      }
    ],
    "name": "RewardsConfigured",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "accounts",
    "outputs": [
      {
        "internalType": "string",
        "name": "nickname",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "profilePicture",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "createdMemecoinsCount",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "allMemecoins",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "allMemecoinsCount",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "startIndex",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "endIndex",
        "type": "uint256"
      }
    ],
    "name": "allMemecoinsRange",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "allQuoteAssets",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "coinCreator",
    "outputs": [
      {
        "internalType": "contract CoinCreator",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "symbol",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "description",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "image",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "socials",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "quoteAsset",
            "type": "address"
          },
          {
            "internalType": "uint256",
            "name": "preBuy",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "creatorFeeRecipient",
            "type": "address"
          },
          {
            "internalType": "uint16",
            "name": "creatorTaxBps",
            "type": "uint16"
          },
          {
            "internalType": "uint16",
            "name": "rewardFeeBps",
            "type": "uint16"
          },
          {
            "internalType": "bool",
            "name": "shareFeesWithHolders",
            "type": "bool"
          }
        ],
        "internalType": "struct CoinDeployer.LaunchParams",
        "name": "params",
        "type": "tuple"
      },
      {
        "internalType": "address[]",
        "name": "snipeExemptions",
        "type": "address[]"
      }
    ],
    "name": "deploy",
    "outputs": [
      {
        "internalType": "address",
        "name": "memecoin",
        "type": "address"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "erc20Parameters",
    "outputs": [
      {
        "components": [
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "symbol",
            "type": "string"
          }
        ],
        "internalType": "struct IERC20ParametersPacker.ERC20Parameters",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "feeEscrow",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "feeTerms",
    "outputs": [
      {
        "internalType": "uint16",
        "name": "feeBps",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "protocolShareBps",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "maxCreatorTaxBps",
        "type": "uint16"
      },
      {
        "internalType": "uint16",
        "name": "snipeTaxStartBps",
        "type": "uint16"
      },
      {
        "internalType": "uint32",
        "name": "snipeTaxSeconds",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "symbol",
        "type": "string"
      }
    ],
    "name": "getAddress",
    "outputs": [
      {
        "internalType": "address",
        "name": "memecoin",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "quoteAsset",
        "type": "address"
      }
    ],
    "name": "graduationPrice",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "price",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "memecoin",
        "type": "address"
      }
    ],
    "name": "isMemeCoinLegit",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "memecoin",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      }
    ],
    "name": "isSnipeExempt",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "launchFee",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "listingManager",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "maxSupply",
    "outputs": [
      {
        "internalType": "uint128",
        "name": "",
        "type": "uint128"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "memecoinsByCreators",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "name": "nicknamesToAccounts",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "parameters",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "listingManager",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "reserveToken",
            "type": "address"
          },
          {
            "internalType": "uint96",
            "name": "cap",
            "type": "uint96"
          },
          {
            "internalType": "uint8",
            "name": "reserveDecimals",
            "type": "uint8"
          },
          {
            "internalType": "uint128",
            "name": "virtualQuote",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "virtualTokenReserve",
            "type": "uint128"
          },
          {
            "internalType": "uint128",
            "name": "maxSupply",
            "type": "uint128"
          },
          {
            "internalType": "uint32",
            "name": "coinIndex",
            "type": "uint32"
          },
          {
            "internalType": "address",
            "name": "owner",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "feeEscrow",
            "type": "address"
          },
          {
            "internalType": "address",
            "name": "creatorFeeRecipient",
            "type": "address"
          },
          {
            "internalType": "uint16",
            "name": "feeBps",
            "type": "uint16"
          },
          {
            "internalType": "uint16",
            "name": "protocolShareBps",
            "type": "uint16"
          },
          {
            "internalType": "uint16",
            "name": "creatorTaxBps",
            "type": "uint16"
          },
          {
            "internalType": "uint16",
            "name": "snipeTaxStartBps",
            "type": "uint16"
          },
          {
            "internalType": "uint32",
            "name": "snipeTaxSeconds",
            "type": "uint32"
          },
          {
            "internalType": "address",
            "name": "rewardDistributor",
            "type": "address"
          },
          {
            "internalType": "uint16",
            "name": "rewardFeeBps",
            "type": "uint16"
          },
          {
            "internalType": "string",
            "name": "description",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "image",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "socials",
            "type": "string"
          }
        ],
        "internalType": "struct ICoinDeployer.MemeCoinParameters",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "quoteAssetList",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "quoteAssets",
    "outputs": [
      {
        "internalType": "uint96",
        "name": "cap",
        "type": "uint96"
      },
      {
        "internalType": "uint8",
        "name": "decimals",
        "type": "uint8"
      },
      {
        "internalType": "bool",
        "name": "enabled",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "renounceOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "rewardsImplementation",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "uint16",
            "name": "feeBps",
            "type": "uint16"
          },
          {
            "internalType": "uint16",
            "name": "protocolShareBps",
            "type": "uint16"
          },
          {
            "internalType": "uint16",
            "name": "maxCreatorTaxBps",
            "type": "uint16"
          },
          {
            "internalType": "uint16",
            "name": "snipeTaxStartBps",
            "type": "uint16"
          },
          {
            "internalType": "uint32",
            "name": "snipeTaxSeconds",
            "type": "uint32"
          }
        ],
        "internalType": "struct CoinDeployer.FeeTerms",
        "name": "terms",
        "type": "tuple"
      }
    ],
    "name": "setFeeTerms",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "fee",
        "type": "uint256"
      }
    ],
    "name": "setLaunchFee",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint16",
        "name": "virtualQuoteBps_",
        "type": "uint16"
      },
      {
        "internalType": "uint128",
        "name": "virtualTokenReserve_",
        "type": "uint128"
      },
      {
        "internalType": "uint128",
        "name": "maxSupply_",
        "type": "uint128"
      }
    ],
    "name": "setParameters",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "uint96",
        "name": "cap",
        "type": "uint96"
      },
      {
        "internalType": "bool",
        "name": "enabled",
        "type": "bool"
      }
    ],
    "name": "setQuoteAsset",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "newOwner",
        "type": "address"
      }
    ],
    "name": "transferOwnership",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "nickname",
        "type": "string"
      },
      {
        "internalType": "string",
        "name": "profilePicture",
        "type": "string"
      }
    ],
    "name": "updateAccountInfo",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "virtualQuoteBps",
    "outputs": [
      {
        "internalType": "uint16",
        "name": "",
        "type": "uint16"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "quoteAsset",
        "type": "address"
      }
    ],
    "name": "virtualQuoteOf",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "virtualTokenReserve",
    "outputs": [
      {
        "internalType": "uint128",
        "name": "",
        "type": "uint128"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
